language: csharp
mono: none
dotnet: 2.1
env:
  global:
    - TRAVIS_PACKAGE_VERSION="0.1.$TRAVIS_BUILD_NUMBER"
    - TRAVIS_PACKAGE_FILE="$TRAVIS_BUILD_DIR/package_v$TRAVIS_PACKAGE_VERSION.zip"    
    - HEROKU_TOKEN=$HEROKU_RELEASETOKEN
    - PGSQL_CONSTR=$POSTGRESQL_CONNECTIONSTRING
    
# blacklist
branches:
  except:
    - /untagged-.*/    
      
notifications:
  email:
    on_success: always
    on_failure: always 
    
services:
  - postgresql

script:  
  - dotnet restore
  - dotnet build 

before_deploy:    
  #- psql -V
  #- psql -d $PGSQL_CONSTR -f "$TRAVIS_BUILD_DIR/Solution Items/Install/Sql/All/01_Create_Tables.sql"
  #- psql -d $PGSQL_CONSTR -f "$TRAVIS_BUILD_DIR/Solution Items/Install/Sql/All/02_Modify_Tables.sql"
  #- psql -d $PGSQL_CONSTR -f "$TRAVIS_BUILD_DIR/Solution Items/Install/Sql/All/03_Create_Objects.sql"
  - cd Cohousing.Server.Api\bin\Debug\netcoreapp2.1 && zip -rv9 $TRAVIS_PACKAGE_FILE . && cd .. && cd .. && cd .. & cd ..
deploy:
  - provider: heroku
    api_key: $HEROKU_TOKEN
    app: buske-server-dev
    on:      
      branch: master
      
  - provider: heroku
    api_key: $HEROKU_TOKEN
    app: buske-server-prd
    on:      
      branch: release
  
  - provider: releases
    api_key: $GITHUBPAGES_RELEASETOKEN
    file: "$TRAVIS_PACKAGE_FILE"
    skip_cleanup: true
    name: "v$TRAVIS_PACKAGE_VERSION"
    draft: false
    on:      
      branch: release    

after_deploy:
  - rm $TRAVIS_PACKAGE_FILE